apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-desktop-host-d-airflow
  labels:
    pv-name: pvc-desktop-host-d-airflow
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/run/desktop/mnt/host/d/sharestorage/airflow"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow
  namespace: airflow
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: "pvc-desktop-host-d-airflow"