kind: Namespace
apiVersion: v1
metadata:
  name: minio
  labels:
    name: minio
---
kind: Secret
apiVersion: v1
metadata:
  name: console-admin
  namespace: minio
  labels:
    app: minio
  annotations:
    meta.helm.sh/release-name: minio
    meta.helm.sh/release-namespace: minio
data:
  rootUser: YzRmOWRmZTEK
  rootPassword: M2NhMWY0MzEK
type: Opaque
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio
  namespace: minio
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: "pvc-desktop-host-d-data"