apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-desktop-host-d-data
  labels:
    pv-name: pvc-desktop-host-d-data
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/run/desktop/mnt/host/d/sharestorage"
