apiVersion: v1
kind: Service
metadata:
  name: {{ template "spark-history-server.fullname" . }}
  labels:
    {{- include "spark-history-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Chart.Name }}
  selector:
    {{- include "spark-history-server.selectorLabels" . | nindent 4 }}
