{{ if .Values.existingNfs.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "base.fullname" . }}-{{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Mi
  mountOptions:
  - nfsvers=4.1
  - rsize=1048576
  - wsize=1048576
  - hard
  - timeo=600
  - retrans=2
  - noresvport
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "{{ .Values.existingNfs.nfsServer }}"
    path: "/{{ .Values.existingNfs.nfsShare }}/users/{{ .Release.Namespace | replace "-" "-2d" }}"
  claimRef:
    name: user-{{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
{{ end }}
